"""Tests for the #1595 generated codebase MAP projection."""

from __future__ import annotations

import json
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[2]
_SCRIPTS = _REPO_ROOT / "scripts"
if str(_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS))

import codebase_map  # noqa: E402
import codebase_provider as provider  # noqa: E402


def _write_project_definition(project_root: Path, *, policy: dict | None = None) -> None:
    project_def = project_root / "vbrief" / "PROJECT-DEFINITION.vbrief.json"
    project_def.parent.mkdir(parents=True)
    plan = {
        "title": "Fixture",
        "status": "running",
        "items": [],
        "architecture": {
            "codeStructure": {
                "version": "0.1",
                "modules": [
                    {
                        "id": "app",
                        "name": "App",
                        "purpose": "Application entry points.",
                        "pathGlobs": ["app/**/*.py"],
                    },
                    {
                        "id": "lib",
                        "name": "Library",
                        "purpose": "Shared helpers.",
                        "pathGlobs": ["lib/**/*.py"],
                    },
                ],
                "pathOwnership": [],
                "allowedPatterns": [],
                "projectionManifest": [
                    {
                        "path": ".planning/codebase/MAP.md",
                        "kind": "codebase-map",
                        "source": "plan.architecture.codeStructure",
                        "generated": True,
                    }
                ],
            }
        },
    }
    if policy is not None:
        plan["policy"] = policy
    project_def.write_text(
        json.dumps({"vBRIEFInfo": {"version": "0.6"}, "plan": plan}),
        encoding="utf-8",
    )


def _write_code(project_root: Path) -> None:
    (project_root / "app").mkdir()
    (project_root / "lib").mkdir()
    (project_root / "app" / "main.py").write_text(
        "from lib.util import thing\nthing()\n",
        encoding="utf-8",
    )
    (project_root / "lib" / "util.py").write_text(
        "def thing():\n    return 1\n",
        encoding="utf-8",
    )


def _provider_artifact(project_root: Path) -> dict:
    app_path = project_root / "app" / "main.py"
    return {
        "formatVersion": "codebase-map.v1",
        "contractVersion": "codebase-provider.v1",
        "kind": "codebase-map",
        "provider": {"name": "fixture-provider", "version": "1.0"},
        "source": {
            "projectRoot": str(project_root),
            "contentHashes": {
                "algorithm": "sha256",
                "files": [{"path": "app/main.py", "sha256": provider.file_sha256(app_path)}],
            },
        },
        "modules": [
            {
                "id": "provider-app",
                "name": "Provider App",
                "purpose": "Provider supplied app module.",
                "pathGlobs": ["app/**/*.py"],
                "fileCount": 1,
                "files": ["app/main.py"],
                "derivedFrom": {"files": "provider", "intent": "provider"},
            }
        ],
        "coupling": [],
        "entryPoints": [],
        "languageDistribution": [{"language": "Python", "files": 1, "derivedFrom": "provider"}],
        "degraded": [],
    }


def test_render_codebase_map_includes_projection_sections(tmp_path: Path) -> None:
    _write_project_definition(tmp_path)
    _write_code(tmp_path)
    selection = provider.select_codebase_map(tmp_path)

    rendered = codebase_map.render_codebase_map(selection.artifact)

    assert "AUTO-GENERATED by task codebase:map" in rendered
    assert "Source of truth: vbrief/PROJECT-DEFINITION.vbrief.json" in rendered
    assert "| `app` | App | Application entry points." in rendered
    assert "| `app` | `lib` | heuristic | app/main.py:1 imports lib.util |" in rendered
    assert "## Degraded Signals" in rendered
    assert "`AST-FREE-HEURISTICS`" in rendered


def test_render_codebase_map_falls_back_for_boolean_file_count(tmp_path: Path) -> None:
    _write_code(tmp_path)
    artifact = _provider_artifact(tmp_path)
    artifact["modules"][0]["fileCount"] = True
    artifact["modules"][0]["files"] = ["app/main.py", "app/extra.py"]

    rendered = codebase_map.render_codebase_map(artifact)

    assert (
        "| `provider-app` | Provider App | Provider supplied app module. | "
        "`app/**/*.py` | 2 |"
    ) in rendered


def test_main_writes_projection_manifest_output(tmp_path: Path) -> None:
    _write_project_definition(tmp_path)
    _write_code(tmp_path)

    assert codebase_map.main(["--project-root", str(tmp_path)]) == 0

    output = tmp_path / ".planning" / "codebase" / "MAP.md"
    text = output.read_text(encoding="utf-8")
    assert "AUTO-GENERATED by task codebase:map" in text
    assert "# Codebase MAP" in text


def test_main_refuses_to_clobber_hand_authored_map(tmp_path: Path) -> None:
    _write_project_definition(tmp_path)
    _write_code(tmp_path)
    output = tmp_path / ".planning" / "codebase" / "MAP.md"
    output.parent.mkdir(parents=True)
    output.write_text("# Hand-authored map\n", encoding="utf-8")

    assert codebase_map.main(["--project-root", str(tmp_path)]) == 2
    assert output.read_text(encoding="utf-8") == "# Hand-authored map\n"


def test_main_checks_hand_authored_output_before_provider_selection(
    tmp_path: Path, monkeypatch
) -> None:
    _write_project_definition(tmp_path)
    _write_code(tmp_path)
    output = tmp_path / ".planning" / "codebase" / "MAP.md"
    output.parent.mkdir(parents=True)
    output.write_text("# Hand-authored map\n", encoding="utf-8")

    def fail_if_called(*_args, **_kwargs):
        raise AssertionError("provider selection should not run before output guard")

    monkeypatch.setattr(codebase_map, "select_codebase_map", fail_if_called)

    assert (
        codebase_map.main(
            [
                "--project-root",
                str(tmp_path),
                "--generate-with",
                "fixture-provider --json",
            ]
        )
        == 2
    )


def test_map_uses_policy_provider_artifact_when_fresh(tmp_path: Path) -> None:
    _write_code(tmp_path)
    artifact_path = tmp_path / ".planning" / "codebase" / "provider-map.json"
    artifact_path.parent.mkdir(parents=True)
    artifact_path.write_text(json.dumps(_provider_artifact(tmp_path)), encoding="utf-8")
    _write_project_definition(
        tmp_path,
        policy={
            "projectionProviders": {
                "codebase-map": {
                    "artifactPath": ".planning/codebase/provider-map.json",
                    "expect": {"provider": "fixture-provider", "version": "1.0"},
                }
            }
        },
    )

    assert codebase_map.main(["--project-root", str(tmp_path)]) == 0

    text = (tmp_path / ".planning" / "codebase" / "MAP.md").read_text(encoding="utf-8")
    assert "fixture-provider" in text
    assert "`provider-app`" in text
