#!/usr/bin/env node
/**
 * Capability map: typed overlay on existing registries plus a generated index (#4099).
 *
 * Commands are resolved through `loadCommandRegistries` (#4094). Skills come from
 * the skill pack; help keys from the in-place help registry; docs-site pages from
 * `docs-site/*.html`. The human page is generated. `--check` fails when the overlay
 * disagrees with those registries or the committed page is stale.
 */
import { existsSync, readdirSync, readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  COMMAND_SNIPPET_AUDIENCES,
  COMMAND_SNIPPET_FROZEN_TASK_VERBS,
  loadCommandRegistries,
} from "../deposit/live-procedure-targets.js";
import { containedWrite } from "../fs/contained-write.js";
import { registryData } from "../triage/help/registry-data.js";

export const AUDIENCES = COMMAND_SNIPPET_AUDIENCES;
export type Audience = (typeof AUDIENCES)[number];

export const STATUSES = ["current", "compatibility", "withdrawn", "experimental"] as const;
export type Status = (typeof STATUSES)[number];

export const CANONICAL_KINDS = ["command", "skill-trigger", "document", "none"] as const;
export type CanonicalKind = (typeof CANONICAL_KINDS)[number];

export const CHANGE_CLASSES = ["add", "change", "withdraw"] as const;
export type ChangeClass = (typeof CHANGE_CLASSES)[number];

export const GOTCHA_MAX_CHARS = 280;
export const OVERLAY_REL = join("content", "docs", "capability-overlay.json");
export const INDEX_REL = join("content", "docs", "capabilities.md");
export const SKILL_PACK_REL = join("content", "packs", "skills", "skills-pack-0.1.json");
export const DOCS_SITE_DIR = "docs-site";

const GENERATED_BANNER = [
  "<!-- AUTO-GENERATED by task docs:capability-map -- DO NOT EDIT MANUALLY -->",
  "<!-- Source of truth: content/docs/capability-overlay.json plus existing registries (#4099) -->",
  "<!-- Regenerate with: task docs:capability-map -->",
].join("\n");

export interface CanonicalEntry {
  readonly kind: CanonicalKind;
  readonly id: string;
}

export interface OverlayEntry {
  readonly id: string;
  readonly title: string;
  readonly audience: Audience;
  readonly status: Status;
  readonly in_the_public_index: boolean;
  readonly canonical_entry: CanonicalEntry;
  readonly gotchas: string;
  readonly status_owner?: string;
}

export interface OverlayFile {
  readonly version: 1;
  readonly entries: readonly OverlayEntry[];
}

export interface CapabilityRegistries {
  readonly commands: ReadonlySet<string>;
  readonly skills: ReadonlySet<string>;
  readonly skillTriggers: ReadonlySet<string>;
  readonly helpKeys: ReadonlySet<string>;
  readonly docsSitePages: ReadonlySet<string>;
}

export interface CapabilityMapResult {
  readonly ok: boolean;
  readonly errors: readonly string[];
  readonly markdown: string;
}

function isAudience(value: unknown): value is Audience {
  return typeof value === "string" && (AUDIENCES as readonly string[]).includes(value);
}

function isStatus(value: unknown): value is Status {
  return typeof value === "string" && (STATUSES as readonly string[]).includes(value);
}

function isCanonicalKind(value: unknown): value is CanonicalKind {
  return typeof value === "string" && (CANONICAL_KINDS as readonly string[]).includes(value);
}

export function isPublicIndexMember(entry: OverlayEntry): boolean {
  return (
    entry.in_the_public_index === true &&
    (entry.status === "current" || entry.status === "compatibility") &&
    entry.canonical_entry.kind !== "none"
  );
}

function asNonEmptyString(value: unknown, label: string, errors: string[]): string {
  if (typeof value !== "string" || value.trim().length === 0) {
    errors.push(`${label} must be a non-empty string`);
    return "";
  }
  return value;
}

export function parseOverlayJson(raw: string): { overlay: OverlayFile | null; errors: string[] } {
  const errors: string[] = [];
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw) as unknown;
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    return { overlay: null, errors: [`overlay JSON parse failed: ${message}`] };
  }
  if (parsed === null || typeof parsed !== "object" || Array.isArray(parsed)) {
    return { overlay: null, errors: ["overlay must be a JSON object"] };
  }
  const rec = parsed as Record<string, unknown>;
  if (rec.version !== 1) {
    errors.push("overlay.version must be 1");
  }
  if (!Array.isArray(rec.entries)) {
    errors.push("overlay.entries must be an array");
    return { overlay: null, errors };
  }
  const seen = new Set<string>();
  const entries: OverlayEntry[] = [];
  for (const [index, item] of rec.entries.entries()) {
    const prefix = `entries[${index}]`;
    if (item === null || typeof item !== "object" || Array.isArray(item)) {
      errors.push(`${prefix} must be an object`);
      continue;
    }
    const row = item as Record<string, unknown>;
    const id = asNonEmptyString(row.id, `${prefix}.id`, errors);
    if (id.length > 0) {
      if (seen.has(id)) errors.push(`${prefix}.id duplicate: ${id}`);
      seen.add(id);
    }
    const title = asNonEmptyString(row.title, `${prefix}.title`, errors);
    if (!isAudience(row.audience)) {
      errors.push(`${prefix}.audience must be consumer|maintainer|frozen`);
    }
    if (!isStatus(row.status)) {
      errors.push(`${prefix}.status must be current|compatibility|withdrawn|experimental`);
    }
    if (typeof row.in_the_public_index !== "boolean") {
      errors.push(`${prefix}.in_the_public_index must be a boolean`);
    }
    const canonicalRaw = row.canonical_entry;
    let canonical: CanonicalEntry = { kind: "none", id: "" };
    if (canonicalRaw === null || typeof canonicalRaw !== "object" || Array.isArray(canonicalRaw)) {
      errors.push(`${prefix}.canonical_entry must be an object`);
    } else {
      const canon = canonicalRaw as Record<string, unknown>;
      if (!isCanonicalKind(canon.kind)) {
        errors.push(`${prefix}.canonical_entry.kind must be command|skill-trigger|document|none`);
      }
      if (typeof canon.id !== "string") {
        errors.push(`${prefix}.canonical_entry.id must be a string`);
      } else if (canon.kind !== "none" && canon.id.trim().length === 0) {
        errors.push(`${prefix}.canonical_entry.id is required when kind is not none`);
      } else {
        canonical = { kind: isCanonicalKind(canon.kind) ? canon.kind : "none", id: canon.id };
      }
    }
    if (typeof row.gotchas !== "string") {
      errors.push(`${prefix}.gotchas must be a string`);
    } else if (row.gotchas.length > GOTCHA_MAX_CHARS) {
      errors.push(`${prefix}.gotchas exceeds ${GOTCHA_MAX_CHARS} characters`);
    }
    const statusOwner =
      typeof row.status_owner === "string" && row.status_owner.trim().length > 0
        ? row.status_owner
        : undefined;
    if (row.status === "experimental" && statusOwner === undefined) {
      errors.push(`${prefix}.status_owner is required when status is experimental`);
    }
    if (
      id.length === 0 ||
      title.length === 0 ||
      !isAudience(row.audience) ||
      !isStatus(row.status) ||
      typeof row.in_the_public_index !== "boolean" ||
      typeof row.gotchas !== "string"
    ) {
      continue;
    }
    entries.push({
      id,
      title,
      audience: row.audience,
      status: row.status,
      in_the_public_index: row.in_the_public_index,
      canonical_entry: canonical,
      gotchas: row.gotchas,
      ...(statusOwner !== undefined ? { status_owner: statusOwner } : {}),
    });
  }
  if (errors.length > 0) return { overlay: null, errors };
  return { overlay: { version: 1, entries }, errors };
}

export function loadSkillRegistry(repoRoot: string): {
  skills: Set<string>;
  skillTriggers: Set<string>;
} {
  const skills = new Set<string>();
  const skillTriggers = new Set<string>();
  const path = join(repoRoot, SKILL_PACK_REL);
  if (!existsSync(path)) return { skills, skillTriggers };
  const parsed = JSON.parse(readFileSync(path, "utf8")) as {
    skills?: readonly { id?: unknown; triggers?: readonly unknown[] }[];
  };
  for (const skill of parsed.skills ?? []) {
    if (typeof skill.id === "string" && skill.id.length > 0) {
      skills.add(skill.id);
      skillTriggers.add(skill.id);
    }
    for (const trigger of skill.triggers ?? []) {
      if (typeof trigger === "string" && trigger.length > 0) skillTriggers.add(trigger);
    }
  }
  return { skills, skillTriggers };
}

export function loadHelpKeys(): Set<string> {
  return new Set(Object.keys(registryData.registry));
}

export function loadDocsSitePages(repoRoot: string): Set<string> {
  const dir = join(repoRoot, DOCS_SITE_DIR);
  const pages = new Set<string>();
  if (!existsSync(dir)) return pages;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.isFile() && entry.name.endsWith(".html")) {
      pages.add(`${DOCS_SITE_DIR}/${entry.name}`);
    }
  }
  return pages;
}

export function loadCapabilityRegistries(repoRoot: string): CapabilityRegistries {
  const commands = loadCommandRegistries(repoRoot);
  const commandIds = new Set<string>([
    ...commands.publicTasks,
    ...commands.internalTasks,
    ...commands.preferredCli,
    ...commands.registeredCli,
    ...commands.helpCli,
    ...COMMAND_SNIPPET_FROZEN_TASK_VERBS,
  ]);
  const { skills, skillTriggers } = loadSkillRegistry(repoRoot);
  return {
    commands: commandIds,
    skills,
    skillTriggers,
    helpKeys: loadHelpKeys(),
    docsSitePages: loadDocsSitePages(repoRoot),
  };
}

export function overlayRegistryErrors(
  overlay: OverlayFile,
  registries: CapabilityRegistries,
): string[] {
  const errors: string[] = [];
  for (const entry of overlay.entries) {
    const { kind, id } = entry.canonical_entry;
    if (kind === "none") continue;
    if (kind === "command" && !registries.commands.has(id)) {
      errors.push(`${entry.id}: canonical command ${id} is not in the #4094 command registries`);
    }
    if (
      kind === "skill-trigger" &&
      !registries.skillTriggers.has(id) &&
      !registries.skills.has(id)
    ) {
      errors.push(`${entry.id}: canonical skill-trigger ${id} is not in the skill pack`);
    }
    if (kind === "document" && !registries.docsSitePages.has(id)) {
      errors.push(`${entry.id}: canonical document ${id} is not a public docs-site page`);
    }
  }
  return errors;
}

export function renderCapabilityIndex(overlay: OverlayFile): string {
  const members = overlay.entries.filter(isPublicIndexMember);
  const lines: string[] = [
    GENERATED_BANNER,
    "",
    "# Capability index",
    "",
    "Generated view over existing registries. Overlay: `content/docs/capability-overlay.json`.",
    "Membership: `in_the_public_index` and status `current` or `compatibility` and canonical kind not `none`.",
    "Same-PR documentation rule: [`content/coding/docs.md`](../coding/docs.md) (#447).",
    "",
  ];
  for (const audience of AUDIENCES) {
    const group = members
      .filter((entry) => entry.audience === audience)
      .slice()
      .sort((a, b) => a.title.localeCompare(b.title));
    if (group.length === 0) continue;
    const heading = audience.charAt(0).toUpperCase() + audience.slice(1);
    lines.push(`## ${heading}`, "");
    for (const entry of group) {
      lines.push(`### ${entry.title}`);
      lines.push(`- **Status:** ${entry.status}`);
      lines.push(`- **Canonical:** ${entry.canonical_entry.kind} \`${entry.canonical_entry.id}\``);
      lines.push(`- **Gotchas:** ${entry.gotchas}`);
      lines.push("");
    }
  }
  return `${lines.join("\n").replace(/\n+$/, "")}\n`;
}

export function evaluateCapabilityMap(options: {
  overlay: OverlayFile;
  registries: CapabilityRegistries;
  committedMarkdown?: string;
}): CapabilityMapResult {
  const errors = overlayRegistryErrors(options.overlay, options.registries);
  const markdown = renderCapabilityIndex(options.overlay);
  if (options.committedMarkdown !== undefined) {
    const committed = options.committedMarkdown.replace(/\r\n/g, "\n");
    if (committed !== markdown) {
      errors.push(`STALE: ${INDEX_REL} is out of date — run \`task docs:capability-map\``);
    }
  }
  return { ok: errors.length === 0, errors, markdown };
}

export function loadOverlayFile(repoRoot: string): {
  overlay: OverlayFile | null;
  errors: string[];
} {
  const path = join(repoRoot, OVERLAY_REL);
  if (!existsSync(path)) {
    return { overlay: null, errors: [`missing overlay: ${OVERLAY_REL}`] };
  }
  return parseOverlayJson(readFileSync(path, "utf8"));
}

function resolveFrameworkRoot(): string {
  const env = process.env.DEFT_ROOT;
  if (env) return env;
  return resolve(dirname(fileURLToPath(import.meta.url)), "..", "..", "..", "..");
}

export function parseCapabilityMapArgs(argv: readonly string[]): {
  projectRoot: string | null;
  check: boolean;
  help: boolean;
  error: string | null;
} {
  let projectRoot: string | null = null;
  let check = false;
  let help = false;
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === "--help" || arg === "-h") help = true;
    else if (arg === "--check") check = true;
    else if (arg === "--project-root") {
      const value = argv[i + 1];
      if (value === undefined) {
        return {
          projectRoot: null,
          check,
          help,
          error: "--project-root expected an argument",
        };
      }
      projectRoot = value;
      i += 1;
    } else if (arg?.startsWith("--project-root=")) {
      projectRoot = arg.slice("--project-root=".length);
    } else if (arg?.startsWith("-")) {
      return { projectRoot, check, help, error: `unrecognized arguments: ${arg}` };
    }
  }
  return { projectRoot, check, help, error: null };
}

export function capabilityMapMain(argv: readonly string[] = process.argv.slice(2)): number {
  const parsed = parseCapabilityMapArgs(argv);
  if (parsed.help) {
    process.stdout.write(
      "usage: capability-map [--project-root <dir>] [--check]\n" +
        "  builds content/docs/capabilities.md from content/docs/capability-overlay.json\n",
    );
    return 0;
  }
  if (parsed.error !== null) {
    process.stderr.write(`capability-map: ${parsed.error}\n`);
    return 2;
  }
  const repo = resolve(parsed.projectRoot ?? resolveFrameworkRoot());
  const loaded = loadOverlayFile(repo);
  if (loaded.overlay === null) {
    process.stderr.write(`${loaded.errors.join("\n")}\n`);
    return 2;
  }
  const registries = loadCapabilityRegistries(repo);
  const indexPath = join(repo, INDEX_REL);
  const committed = existsSync(indexPath) ? readFileSync(indexPath, "utf8") : "";
  const result = evaluateCapabilityMap({
    overlay: loaded.overlay,
    registries,
    committedMarkdown: parsed.check ? committed : undefined,
  });
  if (!result.ok) {
    process.stderr.write(`${result.errors.join("\n")}\n`);
    return 1;
  }
  if (parsed.check) {
    process.stdout.write(`OK: ${INDEX_REL} is current\n`);
    return 0;
  }
  containedWrite({
    root: repo,
    target: indexPath,
    data: result.markdown,
    mode: existsSync(indexPath) ? "replace" : "create",
  });
  process.stdout.write(`OK: wrote ${INDEX_REL}\n`);
  return 0;
}

if (process.argv[1] !== undefined && fileURLToPath(import.meta.url) === process.argv[1]) {
  process.exit(capabilityMapMain());
}
