import { basename, dirname, normalize, sep } from "node:path";

/** Generated-spec banner tokens (lockstep with Python ``_precutover.py``). */
export const GENERATED_SPEC_PURPOSE = "<!-- Purpose: rendered specification -->";

export const GENERATED_SPEC_SOURCE_SPEC =
  "<!-- Source of truth: vbrief/specification.vbrief.json -->";

export const GENERATED_SPEC_SOURCE_SPEC_XBRIEF =
  "<!-- Source of truth: xbrief/specification.xbrief.json -->";

export const GENERATED_SPEC_SOURCE_PD =
  "<!-- Source of truth: vbrief/PROJECT-DEFINITION.vbrief.json -->";

export const GENERATED_SPEC_SOURCE_PD_XBRIEF =
  "<!-- Source of truth: xbrief/PROJECT-DEFINITION.xbrief.json -->";

/** True when markdown carries a generated-spec source marker for either layout. */
export function contentHasGeneratedSpecSource(content: string): boolean {
  return (
    content.includes(GENERATED_SPEC_SOURCE_SPEC) ||
    content.includes(GENERATED_SPEC_SOURCE_SPEC_XBRIEF)
  );
}

/** True when markdown carries a generated greenfield PD source marker for either layout. */
export function contentHasGeneratedPdSource(content: string): boolean {
  return (
    content.includes(GENERATED_SPEC_SOURCE_PD) || content.includes(GENERATED_SPEC_SOURCE_PD_XBRIEF)
  );
}

/** Format a source path for a generated artifact banner. */
export function generatedSourcePath(sourcePath: string): string {
  const parent = basename(dirname(sourcePath));
  if (parent === "xbrief" || parent === "vbrief") {
    return `${parent}/${basename(sourcePath)}`;
  }
  return normalize(sourcePath).split(sep).join("/");
}

/** Build a canonical four-line generated-artifact banner from the actual source path. */
export function buildGeneratedArtifactBanner(
  generator: string,
  purpose: string,
  sourcePath: string,
): string {
  return (
    `<!-- AUTO-GENERATED by ${generator} -- DO NOT EDIT MANUALLY -->\n` +
    `<!-- Purpose: ${purpose} -->\n` +
    `<!-- Source of truth: ${generatedSourcePath(sourcePath)} -->\n` +
    `<!-- Regenerate with: ${generator} -->\n`
  );
}

/** Build the greenfield project export banner for the resolved PROJECT-DEFINITION path. */
export function buildExportSpecPdBanner(projectDefPath: string): string {
  return buildGeneratedArtifactBanner(
    "task project:export-spec",
    "rendered specification",
    projectDefPath,
  );
}

export const EXPORT_SPEC_PD_BANNER = buildExportSpecPdBanner(
  "xbrief/PROJECT-DEFINITION.xbrief.json",
);

/** Narratives excluded from stakeholder SPEC/PRD exports (#2013 Wave 0 §5). */
export const STAKEHOLDER_EXCLUDED_NARRATIVE_KEYS = new Set([
  "projectconfig",
  "tech stack",
  "techstack",
  "configuration",
]);

/** Product narrative keys used for migration-fidelity checks (#2005). */
export const PRODUCT_NARRATIVE_KEYS = [
  "ProblemStatement",
  "Goals",
  "UserStories",
  "Requirements",
  "SuccessMetrics",
  "FunctionalRequirements",
  "NonFunctionalRequirements",
  "AcceptanceCriteria",
  "Architecture",
  "EdgeCases",
] as const;

export const PROPOSED_DISCLAIMER_LINES = [
  "_Scopes in this section are ideas, not approved backlog. Promotion to pending is required before work starts._",
  "_Nothing here is in-flight or committed delivery scope._",
] as const;

export const PROPOSED_STATUS_FILTER = new Set(["draft", "proposed"]);
